site_name: dfirws tools
docs_dir: docs
site_dir: site
theme:
  name: material
  features:
    - navigation.expand

nav:
- Home: index.md
- Tools:
  - Overview: tools/index.md
  - Editors:
    - Overview: tools/editors.md
    - Visual Studio Code: tools/pages/editors-visual-studio-code.md
  - Utilities:
    - Overview: tools/utilities.md
    - Sysinternals Suite: tools/pages/utilities-sysinternals-suite.md
