site_name: dfirws tools
docs_dir: docs
site_dir: site
theme:
  name: material
  features:

nav:
- Home: index.md
- Changelog: Changes.md
- Customize Dfirws: Customize-dfirws.md
- Didier Stevens Tools: Didier-Stevens-tools.md
- Getting Started: Getting-started.md
- Jupyter Notebooks: Jupyter-notebooks.md
- KAPE: KAPE.md
- Network Forensics: Network-forensics.md
- Notebook For PE With Ghidra And Capa: Notebook-for-PE-with-Ghidra-and-capa.md
- Obsidian: Obsidian.md
- Samples: Samples.md
- Windows Forensics: Windows-forensics.md
- Investigations:
  - Investigate Email: Investigations/Investigate-Email.md
  - Investigate JavaScript Files: Investigations/Investigate-JavaScript-files.md
  - Investigate MSI Files: Investigations/Investigate-MSI-files.md
  - Investigate Office Files: Investigations/Investigate-Office-files.md
  - Investigate OneNote File: Investigations/Investigate-OneNote-file.md
  - Investigate PDF Files: Investigations/Investigate-PDF-files.md
  - Investigate PE Files: Investigations/Investigate-PE-files.md
  - Investigate PowerShell: Investigations/Investigate-PowerShell.md
  - Investigate ZIP Files: Investigations/Investigate-ZIP-files.md
- Tools:
  - Overview: tools/index.md
  - Development:
    - Overview: tools/development/index.md
    - Win API Search: tools/development/win-api-search.md
  - Didierstevens:
    - Overview: tools/didierstevens/index.md
    - Didier Stevens Suite: tools/didierstevens/didier-stevens-suite.md
  - Editors:
    - Overview: tools/editors/index.md
    - HxD: tools/editors/hxd.md
    - Malcat Lite: tools/editors/malcat-lite.md
    - Visual Studio Code: tools/editors/visual-studio-code.md
  - Files And Apps:
    - Overview: tools/files-and-apps/index.md
    - bulk_extractor: tools/files-and-apps/bulk-extractor.md
    - DensityScout: tools/files-and-apps/densityscout.md
    - TrID: tools/files-and-apps/trid.md
  - Files And Apps Browser:
    - Overview: tools/files-and-apps-browser/index.md
    - NirSoft Browser Utilities: tools/files-and-apps-browser/nirsoft-browser-utilities.md
  - Files And Apps Database:
    - Overview: tools/files-and-apps-database/index.md
    - Neo4j: tools/files-and-apps-database/neo4j.md
  - Files And Apps Email:
    - Overview: tools/files-and-apps-email/index.md
    - Mail Viewer: tools/files-and-apps-email/mail-viewer.md
    - PST Walker: tools/files-and-apps-email/pst-walker.md
  - Files And Apps Office:
    - Overview: tools/files-and-apps-office/index.md
    - LibreOffice: tools/files-and-apps-office/libreoffice.md
    - MiTeC Structured Storage Viewer: tools/files-and-apps-office/mitec-structured-storage-viewer.md
  - Files And Apps Pdf:
    - Overview: tools/files-and-apps-pdf/index.md
    - PDFStreamDumper: tools/files-and-apps-pdf/pdfstreamdumper.md
  - Files And Apps Pe:
    - Overview: tools/files-and-apps-pe/index.md
    - capa Explorer Web: tools/files-and-apps-pe/capa-explorer-web.md
    - pestudio: tools/files-and-apps-pe/pestudio.md
  - Logs:
    - Overview: tools/logs/index.md
    - FullEventLogView: tools/logs/fulleventlogview.md
  - Memory:
    - Overview: tools/memory/index.md
    - Volatility Workbench 2.1: tools/memory/volatility-workbench-2-1.md
    - Volatility Workbench 3: tools/memory/volatility-workbench-3.md
  - Os Android:
    - Overview: tools/os-android/index.md
    - apktool: tools/os-android/apktool.md
  - Os Windows:
    - Overview: tools/os-windows/index.md
    - ProcDOT: tools/os-windows/procdot.md
    - recbin: tools/os-windows/recbin.md
  - Os Windows Registry:
    - Overview: tools/os-windows-registry/index.md
    - RegShot: tools/os-windows-registry/regshot.md
  - Programming:
    - Overview: tools/programming/index.md
    - PHP: tools/programming/php.md
  - Reverse Engineering:
    - Overview: tools/reverse-engineering/index.md
    - Binary Ninja: tools/reverse-engineering/binary-ninja.md
    - FASM: tools/reverse-engineering/fasm.md
  - Sysinternals:
    - Overview: tools/sysinternals/index.md
    - Sysinternals Suite: tools/sysinternals/sysinternals-suite.md
  - Uncategorized:
    - Overview: tools/uncategorized/index.md
    - API Monitor: tools/uncategorized/api-monitor.md
    - Elastic Stack (ELK + Beats): tools/uncategorized/elastic-stack-elk-beats.md
    - JavaFX SDK: tools/uncategorized/javafx-sdk.md
    - MEX: tools/uncategorized/mex.md
    - Nmap: tools/uncategorized/nmap.md
    - Npcap: tools/uncategorized/npcap.md
    - OpenVPN Connect: tools/uncategorized/openvpn-connect.md
    - SQLite Tools: tools/uncategorized/sqlite-tools.md
    - vmss2core: tools/uncategorized/vmss2core.md
    - Windows Terminal (Canary): tools/uncategorized/windows-terminal-canary.md
    - winpmem: tools/uncategorized/winpmem.md
  - Utilities:
    - Overview: tools/utilities/index.md
    - 7-Zip: tools/utilities/7-zip.md
    - DCode: tools/utilities/dcode.md
    - ExifTool: tools/utilities/exiftool.md
    - geolocus-cli: tools/utilities/geolocus-cli.md
    - Graphviz: tools/utilities/graphviz.md
  - Utilities Browsers:
    - Overview: tools/utilities-browsers/index.md
    - Tor Browser: tools/utilities-browsers/tor-browser.md
  - Utilities Crypto:
    - Overview: tools/utilities-crypto/index.md
    - Gpg4win: tools/utilities-crypto/gpg4win.md
    - hashcat: tools/utilities-crypto/hashcat.md
    - VeraCrypt: tools/utilities-crypto/veracrypt.md
  - Utilities Cryptography:
    - Overview: tools/utilities-cryptography/index.md
    - Gpg4win: tools/utilities-cryptography/gpg4win.md
    - hashcat: tools/utilities-cryptography/hashcat.md
    - protodump: tools/utilities-cryptography/protodump.md
    - VeraCrypt: tools/utilities-cryptography/veracrypt.md

- Home: index.md